### ISSUE TITLE
Cannot start if run within a thin / EM based server.

### ISSUE THREAD

**Issue by rebo** [kennethkalmer/ruote-amqp#2]
When using ruote-amqp within a thin / EventMachine based server the server appears to hang.  For instance using thin + rails + route-kit + route-amqp.

This occurs when calling in an initializer:

```
RuoteAMQP::Receiver.new(
  RuoteKit.engine,
  :launchitems => false
)
```

I've tracked this down to the call RouteAMQP#start! which blocks waiting for AMQP#start to succeed.  But if the EM's reactor is not fully running then AMQP#start will never succeed and we get deadlock.

A work around ive found is with the following monkey patch:

```
module RuoteAMQP
  class Receiver < Ruote::Receiver
    def initialize( engine_or_storage, opts = {} )

      super( engine_or_storage )

      @launchitems = opts[:launchitems]

      @queue = 'ruote_workitems'
      @queue = 'ruote_launchitems' if @launchitems == :only
      @queue = opts[:queue] if opts[:queue]
      Thread.new do 

        until EM.reactor_running?
          sleep 1
        end
        RuoteAMQP.start!

        MQ.queue( @queue ).unsubscribe # taking over...
        sleep 0.3

        MQ.queue( @queue, :durable => true ).subscribe do |message|
          if AMQP.closing?
            # do nothing, we're going down
          else
            handle( message )
          end
        end

      end
    end
  end
end
```

This waits for the EM.reactor_running to return true before starting AMQP.  I'm sure this is not the best solution for thin but it may point you in the right direction.  Of-course this will break functionality if not using thin, so yeah a hack.

**Comment by jmettraux** [comment]
Hello Rebo,

many thanks for this issue report.

The bulk of the work for ruote-amqp has moved to

  https://github.com/jmettraux/ruote-amqp

Do you think that your trick come made more reliable ?

For instance, it could use

```
if defined?(Thin)
```

There are probably other ways to determine how to behave...

Many thanks,

John

**Comment by rebo** [comment]
Hey john didn't realise there was another repository for ruote-amqp, ill check it out.  I don't think this method is hugely reliable mainly because I don't understand Event Machine well enough to know how this may affect it.  I'll investigate the issue a bit more though and see if I can figure out what is going on.

**Comment by jmettraux** [comment]
Yes, sorry. It's pointed at via

  http://ruote.rubyforge.org/source.html
