### ISSUE TITLE
CHANNEL_ERROR - unexpected method in connection state running in AMQP::Protocol::Channel::Open

### ISSUE THREAD

**Issue by weifeng365** [kennethkalmer/ruote-amqp#3]
I run into the following error after sending more 33,000 AMQP messages, and this error can be reproduced. I dig into ruote-amqp lib codes and discover that root cause is in RuoteAMQP::Participant. It always creates a new MQ object (or instance) when method consume is called in this participant, even though the same queue is called. Because this dispatch is in different thread (reference to method dispatch in Ruote::DispatchPool) and MQ object can't be closed, many channels exist after a lot of times of calling of participant's consume. Should RuoteAMQP::Participant add a new method 'do_not_thread' similar to Ruote::StorageParticipant to fix this issue?

CHANNEL_ERROR - unexpected method in connection state running in AMQP::Protocol::Channel::Open

**Comment by jmettraux** [comment]
Hello,

you could easily test by yourself if "do_not_thread" works.

Please tell me how it works. I will then take measures (documentation, code, etc).

John

**Comment by weifeng365** [comment]
hi, yes. I has tested "do_not_thread" by myself and it works well.
You can reproduce this issue. You can discover that MQ is just create once even if the same queue is called a lot of times.

**Comment by jmettraux** [comment]
OK, many thanks for the confirmation.

I will fix that then.

**Comment by jmettraux** [comment]
P.S. the development repository of ruote-amqp is at https://github.com/jmettraux/ruote-amqp/

**Comment by jmettraux** [comment]
Wait, I have looked at the code, it does not necessarily create a new queue per thread. It is not thread-bound at all.

Look at

  https://github.com/jmettraux/ruote-amqp/blob/ruote2.1/lib/ruote-amqp/participant.rb#L139-189

Maybe you guys are passing a new queue each time.

**Comment by jmettraux** [comment]
And the AMQP code is simple :

  https://github.com/tmm1/amqp/blob/master/lib/mq.rb#L677-679

Writing a test anyway...

**Comment by weifeng365** [comment]
hi, in fact it creates a MQ object every time because MQ is thread-bound.

https://github.com/tmm1/amqp/blob/master/lib/mq.rb#L830-833

**Comment by jmettraux** [comment]
Well spotted. 

I guess I will make do_not_thread #=> true the default. I'm working on renovating the specs, I should be done by tomorrow.

Many thanks,

**Comment by jmettraux** [comment]
Hello,

fixed at

  https://github.com/jmettraux/ruote-amqp/commit/14c3b982fa9fc26e0184f404b4e6384548b2f2e8

Many thanks !
