### ISSUE TITLE
some concerns about our use of AMQP

### ISSUE THREAD

**Issue by jmettraux** [kennethkalmer/ruote-amqp#5]
Hello guys,

I'm 100% clueless about AMQP, rabbitmq and ruote-amqp, but I'm trying to help.

I saw some critics with respect to the way we use AMQP in ruote-amqp. I hope @lvader will voice his concerns in a more consistent way, but here's the gist of it:

  https://twitter.com/lvader/status/113988973910691840
  https://twitter.com/jmettraux/status/114064093777903616
  https://twitter.com/lvader/status/115738021403426816

We certainly have something to learn.

Now, regarding

> lvader: @jmettraux first idea is that relaying on default empty exchange might be not the best thing. Have you tried to use it with rabbitmq 2.x ?

What's wrong with this technique ? Is that totally un-khosher in AMQP ? Why would rabbitmq 2.x vs rabbitmq 2.x vs another-amqp-implementation matter ?

Cheers,

John

**Comment by kad** [comment]
Regarding rabbitmq versions: I'll try to reproduce error that my colleague was getting then using rabbitmq 2.2.x + route-amqp 2.2.0 and ruote-amqp-pyclient-1.12. Something in defaults was changed during rabbitmq 1.8 - 2.2 that prevented that setup with both Ruby/Python clients to work correctly.

PS. I'm @lvader at twitter :)

**Comment by kad** [comment]
If I remember correctly, this error was related to requirement from AMQP 0-9-1 spec: "The server MUST NOT allow clients to access the default exchange except by specifying an empty exchange name in the Queue.Bind and content Publish methods." In route-amqp as I can briefly looked, exchange is not explicitly specified.

**Comment by jmettraux** [comment]
Excellent, we have something to work on then. Many thanks.

**Comment by kad** [comment]
There is another thing which bothers me in route-amqp, is inconsistency of using terms, and mixing them. E.g. there is "queue" in ruote terms, there is "queue" in AMQP terms, which means a bit different thing. There is also "routing_key", and it seems that route's "queue" is used both as queue name and routing_key on AMQP side. 
Unfortunately don't know is that really consistent or not, as I'm mostly using route-amqp/python-route-amqp SW maintained by another team, and not looked precisely into that code. It might be that I'm simple wrong, because as mostly Python programmer misunderstood something in Ruby code, and would be happy to hear that :)

**Comment by jmettraux** [comment]
Hello,

there is no concept of "queue" in ruote itself. Maybe what you're seeing is ruby amqp's queue. Ruote-amqp is not using the latest version of ruby amqp. IIRC the later versions of that library are way simpler in how they make the AMQP concepts available.

For the routing_key and all, I'm afraid I can't answer. I hope Kenneth and team will chime in at some point.

Anyway, thanks for the great feedback,

John

**Comment by akeem** [comment]
I might be able to add some light on the routing key stuff. In general when publishing a message to an exchange, you may not know the name of the queue in which the message will end up. Sending a message with a routing key ensures that your message will end up in the queue with the associated routing_key(depending on exchange type).

If you are binding to an un-named exchange, then your queues should be bound to the amq.direct exchange. The routing keys will need to match the names of the queues for proper routing of messages.

**Comment by jmettraux** [comment]
cc @lbt

**Comment by jmettraux** [comment]
If you one of could translate that in a pull request, that'd be much welcome.

**Comment by kad** [comment]
@akeem, you're right about not knowing queue name. However, in case of AMQP, you shouldn't care which is the queue name at all. You need to know correct routing key. So, for example if you need RPC-like queue, then all clients that consume messages for specific routing key should have exactly the same queue name and binding. But, if you some time need situations that for certain work items you need to do multiple actions, then consumers should have their own, exclusive queues bound to the same routing key/exchange. For us, one of the issues was in the code that we inherited in our project is that routing key and queue name was the same and used interchangeable in the code.

**Comment by jmettraux** [comment]
could have we been mislead by the AMQP library we are using ? It should be enforcing AMQP techniques on us.

**Comment by akeem** [comment]
I believe that might have been the case, the previous version of the amqp gem was very liberal in the way it allowed setup

**Comment by bartosh** [comment]
I am able to reproduce the error kad was talking about. Here is traceback:
Traceback (most recent call last):
  File "/usr/bin/boss-participant-gerrit", line 190, in <module>
    sys.exit(main())
  File "/usr/bin/boss-participant-gerrit", line 185, in main
    run_participant(config)
  File "/usr/bin/boss-participant-gerrit", line 140, in run_participant
    config.get('obs_webui'))
  File "/usr/bin/boss-participant-gerrit", line 35, in **init**
    amqp_routing_key=amqp_settings['amqp_routing_key'])
  File "/usr/lib/python2.7/site-packages/RuoteAMQP/participant.py", line 53, in **init**
    auto_delete=False)
  File "/usr/lib/python2.7/site-packages/amqplib/client_0_8/channel.py", line 843, in exchange_declare
    (40, 11),    # Channel.exchange_declare_ok
  File "/usr/lib/python2.7/site-packages/amqplib/client_0_8/abstract_channel.py", line 105, in wait
    return amqp_method(self, args)
  File "/usr/lib/python2.7/site-packages/amqplib/client_0_8/channel.py", line 273, in _close
    (class_id, method_id))
amqplib.client_0_8.exceptions.AMQPChannelException: (403, u'ACCESS_REFUSED - operation not permitted on the default exchange', (40, 10), 'Channel.exchange_declare')

The code it's crashing on is this:
          self._chan = self._conn.channel()

```
      # Declare a shareable queue for the participant
      self._chan.queue_declare(queue=ruote_queue, durable=True,
                               exclusive=False, auto_delete=False)

      # Currently ruote-amqp uses the anonymous direct exchange
      self._chan.exchange_declare(exchange="", type="direct", durable=True,
                                  auto_delete=False)
```

Any ideas how to fix it?

**Comment by bartosh** [comment]
rabbitmq-server version is 2.6.1 and the exact line of code caused the crash is:
self._chan.exchange_declare(exchange="", type="direct", durable=True, auto_delete=False)

**Comment by jmettraux** [comment]
I will try to find some time next week to update ruote-amqp to the latest ruby amqp and then I'll try to work with something else than the default exchange.

Thanks for the details,

John

**Comment by lbt** [comment]
@bartosh ... that's the python ruote amqp client. This issue tracker is for the ruby side :)
For various reasons we don't have a sane bug-track location yet :(
Could you raise this on the mailing list and we'll look at it there.

@kad I've been discussing this with bartosh on the mailing list. The current model in ruote-amqp uses the 1:1 routing-key:queue relationship of a direct exchange and hence the terminology may be a tad fuzzy in places. This is sane and sensible. Permitting fanout at the AMQP level would result in multiple replies to the ruote engine and that would be bad. AMQP does permit multiple subscribers to a queue and we do use that.

**Comment by kad** [comment]
@lbt, question is not about python or ruby code. In theory, those two codebases should work together without problems. The actual issue is that all current code in both implementations relays on assumption that you can create queue, and bind it to default exchange. This was possible in AMQP 0-8 standard, but in case of 0-9-1 server (like in rabbitmq 2.x+) it would refuse any tries to re-declare nameless exchange or explicitly bind any queue to nameless exchange. And it's also not the question of using type=fanout or not. Relying on default binding on the server side is really bad thing, as we can se from AMQP specs changes. The overall idea of this discussion is to have possibility to have queue name and routing key different. E.g. for debugging or logging purposes you can have participant that would be receiving copies of work items but do not send replies. As soon as you start having these cases, all other pieces of code fall as house made of playing cards.

**Comment by bartosh** [comment]
my 2 cents:
Exchange would be also good to specify. This would increase flexibility and scalability a lot.

**Comment by lbt** [comment]
@kad They did - and do - work together without problems on AMQP 0.8 which is what they were written for and tested on. At the time it was a part of the spec and was supported. 0.8 had the concept of a virtual host which meant that using the default exchange on a specific virtual host made sense and was the recommended solution iirc.

Now the spec has changed and virtual hosts are deprecated, I quite agree about the exchange thing ... you may notice that the comments in the python code were a little suspicious of the default exchange thing at the time. Now I know the codebase better I'm happy to agree it's not the best choice and ruote-amqp should use a well known exchange ("ruote" ?) which could be overridden. 

On the other matter , you said "consumers should have their own, exclusive queues bound to the same routing key/exchange." - that sounded like a one to many == fanout-like arrangement so I apologise if that's not what was meant. I discussed your problem with Ed on private mail and it won't work with ruote as each participant would attempt to reply_to_engine against the same workitem.

I would advise against hijacking the ruote-amqp transport as a hackish way to send workitems elsewhere for logging. Ruote has a trace capability already and we're looking to use that.

So "to have queue name and routing key different" doesn't make sense for the ruote-amqp workitem distribution protocol IMHO. Of course that doesn't mean that it is wrong for other uses.

**Comment by kad** [comment]
@lbt David, forget everything that you discussed with Ed on private matter. I'm speaking about generic good programming practice which says that program should not relay on uninitialized defaults if those defaults can be changed in underlying layers without warning. Correctly working AMQP client should have following parameters: hostname, tcp port, username, password, vhost, exchange, queue, routing_key. Relying on any of those parameters on defaults (or default bindings) would lead to problems. If not now, then later.

**Comment by jmettraux** [comment]
Moving on:  http://groups.google.com/group/openwferu-users/browse_thread/thread/d4a23a3fa841a11e
