### ISSUE TITLE
amqp 0.8, 0.9, ..

### ISSUE THREAD

**Issue by semarco** [kennethkalmer/ruote-amqp#6]
Hi, 
is there any developing towards newer amqp versions in progress?
Thank you,
Marco

**Comment by jmettraux** [comment]
Yes, but no workforce.

Sorry and best regards,

John

**Comment by jmettraux** [comment]
Started work on it anyway:  http://groups.google.com/group/openwferu-users/browse_thread/thread/d4a23a3fa841a11e

**Comment by semarco** [comment]
Great news! :-)
